import React, { useState } from 'react';
import { Download, FileText } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

const PlanGenerator: React.FC = () => {
  const { language } = useLanguage();
  const [condition, setCondition] = useState('');
  const [name, setName] = useState('');

  const handleGenerate = () => {
    if (!condition || !name) return;
    // Simulate generation / print
    window.print();
  };

  return (
    <div className="card" style={{ maxWidth: 500, margin: '0 auto' }}>
      <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
        <FileText className="text-secondary" />
        {language === 'en' ? 'Plan Generator' : 'پلان جنریٹر'}
      </h3>
      <p className="text-muted" style={{ marginBottom: '1.5rem' }}>
        {language === 'en' 
          ? 'Generate a downloadable PDF layout of your recommended diet & workout plan.' 
          : 'اپنی تجویز کردہ غذا اور ورزش کے منصوبے کا ڈاؤن لوڈ کے قابل پی ڈی ایف لے آؤٹ تیار کریں۔'}
      </p>

      <div className="form-group">
        <label className="form-label">{language === 'en' ? 'Your Name' : 'آپ کا نام'}</label>
        <input 
          type="text" 
          className="form-input" 
          value={name} 
          onChange={(e) => setName(e.target.value)} 
          placeholder={language === 'en' ? 'Enter full name' : 'پورا نام درج کریں'}
        />
      </div>

      <div className="form-group">
        <label className="form-label">{language === 'en' ? 'Select Condition' : 'بیماری منتخب کریں'}</label>
        <select 
          className="form-input" 
          value={condition} 
          onChange={(e) => setCondition(e.target.value)}
        >
          <option value="" disabled>{language === 'en' ? '-- Select --' : '-- منتخب کریں --'}</option>
          <option value="Diabetes">Diabetes</option>
          <option value="Hypertension">Hypertension</option>
          <option value="PCOD">PCOD</option>
          <option value="Thyroid">Thyroid</option>
          <option value="General Health">General Health</option>
        </select>
      </div>

      <button className="btn btn-secondary" style={{ width: '100%' }} onClick={handleGenerate}>
        <Download size={18} />
        {language === 'en' ? 'Generate & Print PDF' : 'پی ڈی ایف پرنٹ کریں'}
      </button>

      {/* Hidden print area representation */}
      <div className="print-only" style={{ display: 'none' }}>
        <h2>Health Plan for {name}</h2>
        <p>Condition: {condition}</p>
        <p>Generated by HealthGuide</p>
      </div>
    </div>
  );
};

export default PlanGenerator;
